/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei/useGLTF'
import { PerspectiveCamera } from '@react-three/drei/PerspectiveCamera'

import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader'

export default function Model(props) {
  const { material } = props
  const group = useRef()
  const { nodes, materials } = useGLTF('/3d/models/facefull.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <PerspectiveCamera
        makeDefault={false}
        far={10000}
        near={0}
        fov={31.42}
        position={[0, 0, 0.01]}
        rotation={[-0.03, 0.09, 0]}
      />
      <mesh
        // material={materials.DefaultMaterial}
        material={material}
        geometry={nodes.Sphere_2.geometry}
        position={[0, 0, 0]}
      />
      <mesh
        material={material}
        geometry={nodes.Sphere_1.geometry}
        position={[0, 0, 0]}
      />
      <mesh
        material={material}
        geometry={nodes.Sphere.geometry}
        position={[0, 0, 0]}
      />
      <mesh
        material={material}
        geometry={nodes.obj_50879273.geometry}
        position={[0, 0, 0]}
      />
    </group>
  )
}

useGLTF.preload('/3d/models/facefull.glb')
